spring:
  application:
    name: aegisx-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.brubyjknecmleyrlnhbd&password=SU7198UD5BJyJtJ4&stringtype=unspecified&stringtype=unspecified
    username: postgres
    password: SU7198UD5BJyJtJ4
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: '2'
    validate-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:supersecretkeythatisverylongandsecureenoughforHS512algorithm1234567890}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

gemini:
  api:
    key: ${GEMINI_API_KEY:}